version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: portfolio-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - portfolio-network
    restart: unless-stopped

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: portfolio-backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/portfolio
      - JWT_SECRET=your_jwt_secret
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    networks:
      - portfolio-network
    restart: unless-stopped

  # Frontend service
  frontend:
    build:
      context: ./frontend/portfolio-app
      dockerfile: Dockerfile
    container_name: portfolio-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - portfolio-network
    restart: unless-stopped

networks:
  portfolio-network:
    driver: bridge

volumes:
  mongodb_data: 